/**
 * The care schedule — what a cat needs next, derived from what the record
 * already knows (MRC-UX §W9, the retention engine).
 *
 * Pure and deterministic: the API materialises these drafts into CareTask
 * rows (idempotent on catId + seriesKey) and the web renders the same states.
 *
 * MEDICAL HONESTY. Moracat does not set vaccination schedules. Three kinds of
 * tasks exist, and only the first two are generated by default:
 *
 *   1. RECORDED — a due date that is already in the cat's record (a clinic or
 *      the owner wrote "next dose on …"). We only remind; we decided nothing.
 *   2. ROUTINE — non-medical cadence: weigh-ins (monthly for kittens,
 *      quarterly for adults) and a yearly check-up visit.
 *   3. PROPOSED — a kitten vaccination series from `KITTEN_PROTOCOL`. It is
 *      generated ONLY when `protocolApproved` is true (env
 *      CARE_PROTOCOL_APPROVED=1, set after a veterinarian signs the protocol
 *      off), and is always marked `proposed` so the UI says «مقترح — راجع طبيبك».
 */

export type CareKind = "VACCINE" | "CHECKUP" | "WEIGH_IN" | "DEWORM" | "FLEA" | "DENTAL" | "CUSTOM";

export interface CareTaskDraft {
  kind: CareKind;
  /** Stable identity of this task within the cat — the upsert key. */
  seriesKey: string;
  title: { ar: string; en: string };
  dueAt: Date;
  /** True for tasks from an unapproved/advisory protocol — "ask your vet". */
  proposed: boolean;
  linkedVaccinationId?: string;
}

export interface CareInput {
  now: Date;
  birthDate: Date | null;
  /** When the cat joined Moracat — the anchor when nothing else is known. */
  joinedAt: Date;
  vaccinations: { id: string; name: string; administeredAt: Date; dueAt: Date | null }[];
  lastWeighInAt: Date | null;
  lastCheckupAt: Date | null;
  /** CARE_PROTOCOL_APPROVED — a vet has signed off KITTEN_PROTOCOL. */
  protocolApproved: boolean;
}

const DAY = 86_400_000;
const addDays = (d: Date, n: number) => new Date(d.getTime() + n * DAY);
const isoDay = (d: Date) => d.toISOString().slice(0, 10);

export function ageInWeeks(birthDate: Date | null, now: Date): number | null {
  if (!birthDate) return null;
  return Math.floor((now.getTime() - birthDate.getTime()) / (7 * DAY));
}

/**
 * Kitten series, for illustration of the mechanism ONLY until signed off.
 * `vetApproved` stays false in code; approval is an environment decision so it
 * can be granted (or withdrawn) without a deploy, and is recorded in the
 * readiness panel. Weeks are counted from birth.
 */
export const KITTEN_PROTOCOL = {
  vetApproved: false,
  doses: [
    { key: "core-1", weeks: 8, title: { ar: "الجرعة الأساسية الأولى للقطط الصغيرة", en: "First core kitten dose" } },
    { key: "core-2", weeks: 12, title: { ar: "الجرعة الأساسية الثانية", en: "Second core kitten dose" } },
    { key: "core-3", weeks: 16, title: { ar: "الجرعة الأساسية الثالثة", en: "Third core kitten dose" } },
  ],
} as const;

/** Normalise a vaccine name into a key: "Rabies " and "rabies" are one series. */
function nameKey(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, "-").slice(0, 60);
}

export function generateCareTasks(input: CareInput): CareTaskDraft[] {
  const { now } = input;
  const drafts: CareTaskDraft[] = [];
  const weeks = ageInWeeks(input.birthDate, now);
  const isKitten = weeks != null && weeks < 52;

  // 1 · RECORDED — the latest dose of each vaccine that carries a next date.
  const latest = new Map<string, CareInput["vaccinations"][number]>();
  for (const v of input.vaccinations) {
    const k = nameKey(v.name);
    const prev = latest.get(k);
    if (!prev || v.administeredAt > prev.administeredAt) latest.set(k, v);
  }
  for (const [k, v] of latest) {
    if (!v.dueAt) continue;
    drafts.push({
      kind: "VACCINE",
      seriesKey: `vaccine:${k}:${isoDay(v.dueAt)}`,
      title: { ar: v.name, en: v.name },
      dueAt: v.dueAt,
      proposed: false,
      linkedVaccinationId: v.id,
    });
  }

  // 2 · ROUTINE — weigh-ins. One open weigh-in at a time, keyed by the
  // weigh-in it follows, so logging a weight closes it and opens the next.
  const weighEvery = isKitten ? 30 : 90;
  const weighAnchor = input.lastWeighInAt ?? input.joinedAt;
  drafts.push({
    kind: "WEIGH_IN",
    // Anchor kind + exact instant: the first weigh-in after joining and the one
    // after a same-day weigh-in must never share a key.
    seriesKey: input.lastWeighInAt ? `weigh-in:after:${weighAnchor.toISOString()}` : `weigh-in:joined:${weighAnchor.toISOString()}`,
    title: { ar: "وزن شهري", en: "Weigh-in" },
    dueAt: input.lastWeighInAt ? addDays(input.lastWeighInAt, weighEvery) : addDays(input.joinedAt, 7),
    proposed: false,
  });
  if (!isKitten) drafts[drafts.length - 1]!.title = { ar: "وزن كل ثلاثة أشهر", en: "Quarterly weigh-in" };

  // ROUTINE — a yearly check-up visit (wellness, not a medical protocol).
  const checkupAnchor = input.lastCheckupAt ?? input.joinedAt;
  const checkupDue = input.lastCheckupAt ? addDays(input.lastCheckupAt, 365) : addDays(input.joinedAt, 30);
  drafts.push({
    kind: "CHECKUP",
    seriesKey: input.lastCheckupAt ? `checkup:after:${checkupAnchor.toISOString()}` : `checkup:joined:${checkupAnchor.toISOString()}`,
    title: { ar: "الفحص السنوي عند الطبيب", en: "Yearly check-up" },
    dueAt: checkupDue,
    proposed: false,
  });

  // 3 · PROPOSED — kitten series, only with a signed-off protocol, only for a
  // kitten young enough, and only when no vaccine has been recorded at all
  // (once a clinic is involved, the clinic's dates rule).
  if (input.protocolApproved && input.birthDate && weeks != null && weeks < 20 && input.vaccinations.length === 0) {
    for (const d of KITTEN_PROTOCOL.doses) {
      const due = addDays(input.birthDate, d.weeks * 7);
      if (due.getTime() < now.getTime() - 14 * DAY) continue;
      drafts.push({ kind: "VACCINE", seriesKey: `kitten:${d.key}`, title: { ...d.title }, dueAt: due, proposed: true });
    }
  }

  return drafts;
}

// ── States ────────────────────────────────────────────────────────────────

export type CareState = "upcoming" | "due" | "overdue" | "done" | "skipped";

/** The "due" window — inside a week counts as due. */
export const CARE_DUE_WINDOW_DAYS = 7;

export function careState(task: { status: string; dueAt: Date | string }, now: Date = new Date()): CareState {
  if (task.status === "DONE") return "done";
  if (task.status === "SKIPPED") return "skipped";
  const due = new Date(task.dueAt).getTime();
  if (due < now.getTime() - DAY / 2) return "overdue";
  if (due - now.getTime() <= CARE_DUE_WINDOW_DAYS * DAY) return "due";
  return "upcoming";
}

/** Bilingual labels for each state (words + shape, never colour alone — R093). */
export const CARE_STATE_LABELS: Record<CareState, { ar: string; en: string }> = {
  upcoming: { ar: "قادم", en: "Upcoming" },
  due: { ar: "مستحق", en: "Due" },
  overdue: { ar: "متأخر", en: "Overdue" },
  done: { ar: "تم", en: "Done" },
  skipped: { ar: "تم تخطيه", en: "Skipped" },
};
